import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { canonicalizeGraph, fixtureGraphOutput } from "./modeling-graph.mjs";
import { preflightBrepGraph } from "./brep-preflight.mjs";

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, "../../../../../");
const python = process.env.NET30_CADQUERY_BIN || path.join(repo, ".cadquery-venv/bin/python");
const temporary = await fs.mkdtemp(path.join(os.tmpdir(), "net30-cad-proof-"));
try {
  const output = fixtureGraphOutput({ product: { name: "DURAN proof" }, prompt: "100 mL bottle", requestedComponents: ["유리병"], imageIds: [] });
  const canonical = canonicalizeGraph(output, ["유리병"], []); const component = canonical.graph.components[0];
  const stem = path.join(temporary, component.id); const requestPath = path.join(temporary, "request.json");
  await fs.writeFile(requestPath, JSON.stringify({ graphComponent: component, graphNodes: canonical.graph.nodes, paths: { step: `${stem}.step`, brep: `${stem}.brep`, stl: `${stem}.stl`, report: `${stem}.validation.json` }, tessellation: { chordMm: .2, angularDeg: 15 } }));
  const run = spawnSync(python, ["-u", path.join(here, "cad-worker.py"), requestPath], { encoding: "utf8", timeout: 120000 });
  assert.equal(run.status, 0, `${run.stdout}\n${run.stderr}`);
  const report = JSON.parse(await fs.readFile(`${stem}.validation.json`, "utf8"));
  assert.equal(report.valid, true); assert.equal(report.closed, true); assert.ok(report.volumeMm3 > 0); assert.ok(report.boundsMm.z > 90);
  for (const suffix of ["step", "brep", "stl"]) assert.ok((await fs.stat(`${stem}.${suffix}`)).size > 100);
  const curvedGraph = structuredClone(canonical.graph);
  const curvedNode = curvedGraph.nodes.find((node) => node.componentId === component.id && node.parameters.profile?.length >= 4);
  const poles = curvedNode.parameters.profile.filter((point, index, all) => index === 0 || index === all.length - 1 || index % 2 === 0).map(({ xMm, zMm }) => ({ xMm, zMm }));
  curvedNode.parameters.curveSegments = [{ kind: "nurbs", poles, degree: Math.min(3, poles.length - 1), weights: poles.map(() => 1), knots: poles.map((_, index) => index), multiplicities: poles.map(() => 1), periodic: false }];
  const curveStem = path.join(temporary, `${component.id}-nurbs`); const curveRequest = path.join(temporary, "nurbs.request.json");
  await fs.writeFile(curveRequest, JSON.stringify({ graphComponent: component, graphNodes: curvedGraph.nodes, paths: { step: `${curveStem}.step`, brep: `${curveStem}.brep`, stl: `${curveStem}.stl`, report: `${curveStem}.validation.json` }, tessellation: { chordMm: .2, angularDeg: 15 } }));
  const curveRun = spawnSync(python, ["-u", path.join(here, "cad-worker.py"), curveRequest], { encoding: "utf8", timeout: 120000 });
  assert.equal(curveRun.status, 0, `${curveRun.stdout}\n${curveRun.stderr}`);
  const curveReport = JSON.parse(await fs.readFile(`${curveStem}.validation.json`, "utf8"));
  assert.equal(curveReport.valid, true); assert.equal(curveReport.closed, true); assert.ok(curveReport.volumeMm3 > 0, "a declared NURBS generating curve must compile into a closed OCCT B-Rep");
  const capOutput = fixtureGraphOutput({ product: { name: "ribbed closure proof" }, prompt: "ribbed closure", requestedComponents: ["뚜껑"], imageIds: [] });
  const base = capOutput.components[0].features[0];
  base.key = "cap-base"; base.operation = "primitive"; base.inputKeys = [];
  base.parameters = { ...base.parameters, primitive: "cylinder", profile: null, dimensionsMm: null, radiusMm: 25, heightMm: 20, thicknessMm: null, count: null, spacingMm: null, depthMm: null };
  const rib = { ...structuredClone(base), key: "cap-rib", operation: "rib", inputKeys: [base.key], parameters: { ...base.parameters, primitive: null, radiusMm: 25, heightMm: 15, count: null, spacingMm: 1.2, depthMm: 1.4, thicknessMm: null, transform: { translationMm: { x: 0, y: 0, z: 2.5 }, rotationDeg: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 } } } };
  const pattern = { ...structuredClone(base), key: "cap-rib-pattern", operation: "pattern", inputKeys: [base.key, rib.key], parameters: { ...base.parameters, primitive: null, profile: null, radiusMm: null, heightMm: null, count: 36, spacingMm: null, depthMm: null, thicknessMm: null } };
  capOutput.components[0].features = [base, rib, pattern];
  const capCanonical = canonicalizeGraph(capOutput, ["뚜껑"], []); const capComponent = capCanonical.graph.components[0]; const capStem = path.join(temporary, capComponent.id); const capRequest = path.join(temporary, "cap.request.json");
  await fs.writeFile(capRequest, JSON.stringify({ graphComponent: capComponent, graphNodes: capCanonical.graph.nodes, paths: { step: `${capStem}.step`, brep: `${capStem}.brep`, stl: `${capStem}.stl`, report: `${capStem}.validation.json` }, tessellation: { chordMm: .2, angularDeg: 15 } }));
  const capRun = spawnSync(python, ["-u", path.join(here, "cad-worker.py"), capRequest], { encoding: "utf8", timeout: 120000 });
  assert.equal(capRun.status, 0, `${capRun.stdout}\n${capRun.stderr}`);
  const capReport = JSON.parse(await fs.readFile(`${capStem}.validation.json`, "utf8"));
  assert.equal(capReport.valid, true); assert.equal(capReport.closed, true); assert.equal(capReport.solidCount, 1, "a patterned ribbed closure must be fused into one B-Rep solid");
  const preflight = await preflightBrepGraph(capCanonical.graph);
  assert.equal(preflight.ok, true, JSON.stringify(preflight.diagnostics));
  const roofedOutput = fixtureGraphOutput({ product: { name: "roofed closure proof" }, prompt: "tapered ribbed closure", requestedComponents: ["마개"], imageIds: [] });
  const roofBase = roofedOutput.components[0].features[0];
  roofBase.key = "roof-base"; roofBase.operation = "revolve"; roofBase.inputKeys = [];
  roofBase.parameters = { ...roofBase.parameters, primitive: null, profile: [{ xMm: 0, yMm: 0, zMm: 0 }, { xMm: 25, yMm: 0, zMm: 0 }, { xMm: 25, yMm: 0, zMm: 2 }, { xMm: 22, yMm: 0, zMm: 2 }, { xMm: 22, yMm: 0, zMm: 20 }, { xMm: 0, yMm: 0, zMm: 22 }, { xMm: 0, yMm: 0, zMm: 0 }], dimensionsMm: null, radiusMm: null, heightMm: null, thicknessMm: null, count: null, spacingMm: null, depthMm: null };
  const roofShell = { ...structuredClone(roofBase), key: "roof-shell", operation: "shell", inputKeys: [roofBase.key], parameters: { ...roofBase.parameters, profile: null, thicknessMm: 2 } };
  const roofRib = { ...structuredClone(roofBase), key: "roof-rib", operation: "rib", inputKeys: [roofShell.key], parameters: { ...roofBase.parameters, profile: null, heightMm: 15, thicknessMm: null, spacingMm: 1.2, depthMm: 1.4, count: null, transform: { translationMm: { x: 0, y: 0, z: 3 }, rotationDeg: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 } } } };
  const roofPattern = { ...structuredClone(roofBase), key: "roof-rib-pattern", operation: "pattern", inputKeys: [roofShell.key, roofRib.key], parameters: { ...roofBase.parameters, profile: null, heightMm: null, count: 36, spacingMm: null, depthMm: null, thicknessMm: null } };
  roofedOutput.components[0].features = [roofBase, roofShell, roofRib, roofPattern];
  const roofCanonical = canonicalizeGraph(roofedOutput, ["마개"], []); const roofComponent = roofCanonical.graph.components[0]; const roofStem = path.join(temporary, roofComponent.id); const roofRequest = path.join(temporary, "roof.request.json");
  await fs.writeFile(roofRequest, JSON.stringify({ graphComponent: roofComponent, graphNodes: roofCanonical.graph.nodes, paths: { step: `${roofStem}.step`, brep: `${roofStem}.brep`, stl: `${roofStem}.stl`, report: `${roofStem}.validation.json` }, tessellation: { chordMm: .2, angularDeg: 15 } }));
  const roofRun = spawnSync(python, ["-u", path.join(here, "cad-worker.py"), roofRequest], { encoding: "utf8", timeout: 120000 });
  assert.equal(roofRun.status, 0, `${roofRun.stdout}\n${roofRun.stderr}`);
  const roofReport = JSON.parse(await fs.readFile(`${roofStem}.validation.json`, "utf8"));
  assert.equal(roofReport.solidCount, 1, "a roofed shell with surface-following ribs must remain one B-Rep solid");
  const assemblyRequest = path.join(temporary, "assembly.request.json"); const assemblyPaths = { xbf: path.join(temporary, "assembly.xbf"), step: path.join(temporary, "assembly.step"), report: path.join(temporary, "assembly.validation.json") };
  await fs.writeFile(assemblyRequest, JSON.stringify({ name: "DURAN proof", components: [{ id: component.id, brep: `${stem}.brep` }], paths: assemblyPaths, toleranceMm: .01 }));
  const assemblyRun = spawnSync(python, [path.join(here, "cad-assembly-worker.py"), assemblyRequest], { encoding: "utf8", timeout: 120000 });
  assert.equal(assemblyRun.status, 0, `${assemblyRun.stdout}\n${assemblyRun.stderr}`); const assemblyReport = JSON.parse(await fs.readFile(assemblyPaths.report, "utf8"));
  assert.equal(assemblyReport.valid, true); assert.equal(assemblyReport.roundTripWithinTolerance, true); assert.ok((await fs.stat(assemblyPaths.xbf)).size > 100); assert.ok((await fs.stat(assemblyPaths.step)).size > 100);
  console.log("Canonical child B-Rep plus parent XBF/STEP round-trip proof passed.");
} finally { await fs.rm(temporary, { recursive: true, force: true }); }
