import "dotenv/config";
import { createReadStream, existsSync } from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";
import express from "express";
import cors from "cors";
import { NodeStreamableHTTPServerTransport } from "@modelcontextprotocol/node";
import { composeSelectedComponentGlbs, createBlenderMcpServer, modelingPayloadSchema } from "./blender-mcp.mjs";
import { runModelingJob } from "./modeling-agent.mjs";
import { createAssetStorage, IMAGE_TYPES, MAX_IMAGE_BYTES } from "./storage.mjs";
import { COMPONENTS, JOB_STATES, defaultOpenAiModel, openAiModels } from "./modeling-spec.mjs";
import { createVersionStore } from "./version-store.mjs";
import { createDraftStore } from "./draft-store.mjs";
import { analyseDraft, approvedDraftToLegacyPayload, approvalHash, draftPayloadSchema, draftReady } from "./modeling-spec.mjs";

const app = express(); const token = (process.env.NET30_MODELING_HUB_TOKEN ?? "").trim();
const origins = (process.env.NET30_MODELING_ALLOWED_ORIGINS ?? "http://127.0.0.1:5173").split(",").map((value) => value.trim()).filter(Boolean);
const env = (name, fallback = "") => process.env[name]?.trim() || fallback;
const repoRoot = env("NET30_REPO", path.resolve(process.cwd(), "../../../..")); const assetRoot = env("NET30_3D_ASSET_ROOT", path.resolve(repoRoot, "../net30-3d-assets")); const jobsRoot = path.join(assetRoot, "jobs"); const storage = createAssetStorage(assetRoot); const versions = createVersionStore(assetRoot);
const jobs = new Map(); const draftClients = new Map();
const drafts = createDraftStore(assetRoot);
function authorized(req) { if (!token) return true; const local=["127.0.0.1","::1","::ffff:127.0.0.1"].includes(req.socket.remoteAddress ?? ""); return local || req.headers.authorization === `Bearer ${token}`; }
function event(job, state, message, components = job.components) { job.state=state; job.message=message; job.components=components; job.updatedAt=new Date().toISOString(); const detail={ eventId:(job.nextEventId=(job.nextEventId??0)+1),operation:"build",stage:state,state:["complete","review_required"].includes(state)?"complete":state==="failed"?"failed":"running",message,components,at:job.updatedAt }; job.events.push(detail); for (const client of job.clients) client.write(`id: ${detail.eventId}\ndata: ${JSON.stringify(detail)}\n\n`); }
function publicJob(job) { const { clients, promise, ...value }=job; return value; }
function emitDraft(draft, progress = null) { const detail={ eventId:progress?.eventId,state:draft.state,message:draft.message,revision:draft.revision,progress,at:draft.updatedAt }; for (const client of draftClients.get(draft.id)??[]) client.write(`${detail.eventId?`id: ${detail.eventId}\n`:""}data: ${JSON.stringify(detail)}\n\n`); }
async function saveDraft(draft, state, message) { draft.state=state; draft.message=message; draft.revision += 1; await drafts.save(draft); emitDraft(draft); return draft; }
async function progressDraft(draft, progress) { const event=await drafts.appendProgress(draft,progress); emitDraft(draft,event); return event; }
function publicDraft(draft) { return { ...draft, approval: draftReady(draft) }; }
async function getJob(id) { if (jobs.has(id)) return jobs.get(id); const file=path.join(jobsRoot,id,"result.json"); if (!existsSync(file)) return null; const result=JSON.parse(await fs.readFile(file,"utf8")); return { id, state:"complete", message:"저장된 작업", createdAt:"", updatedAt:"", events:[], result }; }
async function serveArtifact(req,res) { const id=req.params.id; const part=(Array.isArray(req.params.path) ? req.params.path.join("/") : req.params.path ?? "").replace(/^\/+/,""); if (!part || part.includes("..")) return res.status(400).json({ok:false,error:"잘못된 artifact 경로입니다."}); const file=path.resolve(jobsRoot,id,part); if (!file.startsWith(`${path.resolve(jobsRoot,id)}${path.sep}`) || !existsSync(file)) return res.status(404).json({ok:false,error:"artifact를 찾을 수 없습니다."}); const ext=path.extname(file); res.set({"content-type":ext===".glb"?"model/gltf-binary":ext===".json"?"application/json":"application/octet-stream","cache-control":"no-store","cross-origin-resource-policy":"cross-origin"}); return createReadStream(file).pipe(res); }
async function resolveComponentSelections(raw) {
  if (!Array.isArray(raw) || raw.length === 0) throw new Error("조립에 포함할 컴포넌트 버전을 선택하세요.");
  const requested = new Map();
  for (const item of raw) {
    const component = typeof item?.component === "string" ? item.component : ""; const versionId = typeof item?.versionId === "string" ? item.versionId : "";
    if (!component || !versionId) throw new Error("선택한 컴포넌트 버전이 올바르지 않습니다.");
    requested.set(component, { component, versionId });
  }
  const selections = [];
  for (const item of requested.values()) {
    const version = await versions.find(item.component, item.versionId);
    if (!version) throw new Error(`${item.component}의 선택한 버전을 찾을 수 없습니다.`);
    selections.push({ component: version.component, versionId: version.id, sourcePath: versions.artifactPath(version.component, version.id) });
  }
  return selections;
}
async function assembleSelections(raw) { return composeSelectedComponentGlbs(await resolveComponentSelections(raw), { assetRoot }); }
function serveGlb(res, file, missingMessage) { if (!existsSync(file)) return res.status(404).json({ok:false,error:missingMessage}); res.set({"content-type":"model/gltf-binary","cache-control":"no-store","cross-origin-resource-policy":"cross-origin"}); return createReadStream(file).pipe(res); }
async function queueJob(payload, { draft = null } = {}) {
  const id=`job-${Date.now()}-${Math.random().toString(36).slice(2,8)}`; const componentState=Object.fromEntries(payload.components.map((component)=>[component,{state:"queued",message:"작업 대기"}]));
  const job={id,payload,draftId:draft?.id??null,state:"researching",message:"작업을 대기열에 추가했습니다.",components:componentState,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),events:[],nextEventId:0,clients:new Set(),result:null}; jobs.set(id,job);
  const imageInputs=await storage.imageInputs(payload.imageIds);
  job.promise=runModelingJob(payload,{jobId:id,imageInputs,onProgress:(state,message,components)=>event(job,state,message,components)}).then(async(result)=>{
    const registered={}; for(const component of payload.components) { const source=path.join(assetRoot,"jobs",id,"components",`${component}.glb`); const spec=result.modelingSpec?.components?.find((item)=>item.componentInstanceId===component); if(existsSync(source)) registered[component]=await versions.register({component,sourcePath:source,jobId:id,contractHash:result.report.contractHash,summary:result.summary,parentVersionId:payload.parentVersionId?.[component]??null,approvedSpec:spec??null,transform:spec?.transform??null,interfaces:spec?.features?.interfaceId?[spec.features.interfaceId]:[]}); }
    result.versions=registered; job.result=result; event(job,result.status,result.status==="review_required" ? "시각 결과와 컴포넌트 버전을 저장했습니다. 제조 승인에는 추가 검토가 필요합니다." : "작업과 컴포넌트 버전 저장이 완료되었습니다.",Object.fromEntries(payload.components.map((component)=>[component,{state:"complete",message:"버전 저장 완료",version:registered[component]?.id??null}])));
    if(draft) { draft.jobId=id; await saveDraft(draft,result.status,"Blender 생성과 검증이 완료되었습니다."); await progressDraft(draft,{operation:"build",stage:"버전 저장",state:"complete",completed:payload.components.length,total:payload.components.length,unit:"components",message:"컴포넌트 버전을 저장했습니다."}); }
    return result;
  }).catch(async(error)=>{job.error=error.message; event(job,"failed",error.message,Object.fromEntries(payload.components.map((component)=>[component,{state:"failed",message:error.message}]))); if(draft) { draft.jobId=id; await saveDraft(draft,"failed",error.message); await progressDraft(draft,{operation:"build",stage:"실패",state:"failed",message:error.message}); }}).finally(()=>{for(const client of job.clients) client.end(); job.clients.clear();}); return job;
}

await fs.mkdir(jobsRoot,{recursive:true}); await storage.initialise(); await drafts.initialise(); await storage.cleanupExpired(); await versions.importLegacyJobs(jobsRoot); await versions.initialiseShowcase(jobsRoot); setInterval(()=>void storage.cleanupExpired(),3600000).unref();
app.use(cors({origin(origin,cb){ if(!origin||origins.includes(origin)) return cb(null,true); return cb(new Error(`허용되지 않은 origin: ${origin}`)); }})); app.use(express.json({limit:"1mb"}));
app.get("/health",(_req,res)=>res.json({ok:true,mode:"assembly-cad-blender-v2",openAiModels:openAiModels(),storage:process.env.AWS_S3_BUCKET_NAME?"railway-bucket":"local-volume",jobStates:JOB_STATES}));
app.get("/api/modeling/schema",(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); return res.json({ok:true,components:COMPONENTS,models:openAiModels(),defaultModel:defaultOpenAiModel(),upload:{maxFiles:4,maxBytes:MAX_IMAGE_BYTES,types:[...IMAGE_TYPES]},manufacturing:"engineer-reviewed candidate only"}); });
app.post("/api/modeling/uploads",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); try { const upload=await storage.createUpload(req.body??{}); return res.status(201).json({ok:true,upload}); } catch(error) { return res.status(400).json({ok:false,error:error.message}); }});
app.put("/api/modeling/uploads/:id",express.raw({type:()=>true,limit:"10mb"}),async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); try { if(!IMAGE_TYPES.has(req.headers["content-type"]??"")) throw new Error("JPEG, PNG, WebP 이미지만 업로드할 수 있습니다."); const upload=await storage.putLocal(req.params.id,req.body,req.headers["content-type"]); return res.json({ok:true,upload:{id:upload.id}}); } catch(error) { return res.status(400).json({ok:false,error:error.message}); }});
app.post("/api/modeling/uploads/:id/complete",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); try { const upload=await storage.markUploaded(req.params.id); return res.json({ok:true,upload:{id:upload.id}}); } catch(error) { return res.status(400).json({ok:false,error:error.message}); }});
app.post("/api/modeling/drafts",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); try { const payload=draftPayloadSchema.parse(req.body??{}); const draft=await drafts.create(payload); res.status(202).json({ok:true,draft:publicDraft(draft),statusUrl:`/api/modeling/drafts/${draft.id}`,eventsUrl:`/api/modeling/drafts/${draft.id}/events`}); void (async()=>{ try { await progressDraft(draft,{operation:"analysis",stage:"이미지 업로드 확인",state:"complete",completed:payload.imageIds.length,total:payload.imageIds.length,unit:"files",message:"모델링 입력 이미지를 확인했습니다."}); await progressDraft(draft,{operation:"analysis",stage:"제품·조립 분석",state:"running",message:"제품과 공통 조립 기준을 분석 중입니다."}); const imageInputs=await storage.imageInputs(payload.imageIds); const analysis=await analyseDraft(payload,imageInputs); await progressDraft(draft,{operation:"analysis",stage:"제품·조립 분석",state:"complete",message:"공통 기준 분석이 완료되었습니다."}); await progressDraft(draft,{operation:"analysis",stage:"컴포넌트 분석",state:"complete",completed:analysis.components.length,total:payload.requestedComponents.length,unit:"components",message:"지정한 컴포넌트를 모두 분석했습니다."}); draft.model=analysis.model; draft.product=analysis.product; draft.components=analysis.components; draft.questions=analysis.questions; draft.stickerSlots=analysis.stickerSlots; await progressDraft(draft,{operation:"analysis",stage:"질문 완전성 검사",state:"complete",completed:analysis.questions.length,total:analysis.questions.length,unit:"questions",message:"필수 승인 질문을 확인했습니다."}); await saveDraft(draft,"awaiting_product_review","제품 식별과 전체 기준값을 검토하세요."); } catch(error) { const message=error instanceof Error?error.message:String(error); await saveDraft(draft,message.startsWith("analysis_incomplete")?"analysis_incomplete":message.startsWith("needs_custom_recipe")?"needs_custom_recipe":"failed",message); await progressDraft(draft,{operation:"analysis",stage:"분석 실패",state:"failed",message}); } })(); } catch(error) { return res.status(400).json({ok:false,error:error.message}); }});
app.get("/api/modeling/drafts/:id",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); const draft=await drafts.get(req.params.id); return draft?res.json({ok:true,draft:publicDraft(draft)}):res.status(404).json({ok:false,error:"초안을 찾을 수 없습니다."}); });
app.get("/api/modeling/drafts/:id/events",async(req,res)=>{ if(!authorized(req)) return res.status(401).end(); const draft=await drafts.get(req.params.id); if(!draft) return res.status(404).end(); res.set({"content-type":"text/event-stream","cache-control":"no-cache",connection:"keep-alive"}); res.flushHeaders(); const after=Number(req.headers["last-event-id"]??0); for(const progress of (draft.progress??[]).filter((item)=>item.eventId>after)) res.write(`id: ${progress.eventId}\ndata: ${JSON.stringify({state:draft.state,message:draft.message,revision:draft.revision,progress})}\n\n`); res.write(`data: ${JSON.stringify({state:draft.state,message:draft.message,revision:draft.revision})}\n\n`); const clients=draftClients.get(draft.id)??new Set(); clients.add(res); draftClients.set(draft.id,clients); const heartbeat=setInterval(()=>res.write(": heartbeat\n\n"),15000); req.on("close",()=>{clearInterval(heartbeat);clients.delete(res);}); });
app.post("/api/modeling/drafts/:id/answers",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); const draft=await drafts.get(req.params.id); if(!draft) return res.status(404).json({ok:false,error:"초안을 찾을 수 없습니다."}); const {expectedRevision,decisions=[]}=req.body??{}; if(expectedRevision!==draft.revision) return res.status(409).json({ok:false,error:"revision_conflict",draft:publicDraft(draft)}); try { await progressDraft(draft,{operation:"approval",stage:"승인 저장",state:"running",completed:0,total:decisions.length,unit:"questions",message:"승인 결정을 저장 중입니다."}); for(const [index,decision] of decisions.entries()) { const item=draft.questions.find((question)=>question.id===decision.questionId); if(!item) throw new Error("질문을 찾을 수 없습니다."); if(!["accept","override","reject","needs_evidence"].includes(decision.action)) throw new Error("지원하지 않는 결정입니다."); item.status=decision.action==="accept"?"accepted":decision.action==="override"?"overridden":decision.action==="reject"?"rejected":"needs_evidence"; if(decision.action==="override") item.userValue=decision.value; if(decision.action==="accept") item.userValue=item.recommendedValue; await drafts.appendDecision(draft.id,{questionId:item.id,action:decision.action,value:item.userValue}); await progressDraft(draft,{operation:"approval",stage:"승인 저장",state:"running",completed:index+1,total:decisions.length,unit:"questions",message:"승인 결정을 저장 중입니다."}); }
    const open=draft.questions.some((item)=>item.required&&!["accepted","overridden"].includes(item.status)); const productOpen=draft.questions.some((item)=>["product","assembly","interface"].includes(item.scope)&&!["accepted","overridden"].includes(item.status)); await saveDraft(draft,productOpen?"awaiting_product_review":open?"awaiting_parameter_review":"ready_to_build",productOpen?"제품·조립 기준값을 모두 확인하세요.":open?"컴포넌트별 기준값을 모두 확인하세요.":"모든 기준값이 승인되었습니다. Blender 생성을 실행할 수 있습니다."); await progressDraft(draft,{operation:"approval",stage:"승인 저장",state:"complete",completed:decisions.length,total:decisions.length,unit:"questions",message:"승인 상태를 저장했습니다."}); return res.json({ok:true,draft:publicDraft(draft)}); } catch(error) { return res.status(400).json({ok:false,error:error.message}); }});
app.put("/api/modeling/drafts/:id/component-tree",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); const draft=await drafts.get(req.params.id); if(!draft) return res.status(404).json({ok:false,error:"초안을 찾을 수 없습니다."}); if(req.body?.expectedRevision!==draft.revision) return res.status(409).json({ok:false,error:"revision_conflict",draft:publicDraft(draft)}); if(!Array.isArray(req.body?.components)||req.body.components.length===0) return res.status(400).json({ok:false,error:"컴포넌트를 하나 이상 선택하세요."}); draft.components=req.body.components; draft.questions=draft.questions.map((item)=>item.scope==="component"?{...item,status:"stale"}:item); await saveDraft(draft,"awaiting_parameter_review","컴포넌트 트리가 변경되어 관련 기준값을 다시 확인해야 합니다."); return res.json({ok:true,draft:publicDraft(draft)}); });
app.post("/api/modeling/drafts/:id/reanalyze",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); const draft=await drafts.get(req.params.id); if(!draft) return res.status(404).json({ok:false,error:"초안을 찾을 수 없습니다."}); if(req.body?.expectedRevision!==draft.revision) return res.status(409).json({ok:false,error:"revision_conflict",draft:publicDraft(draft)}); await saveDraft(draft,"analyzing_parameters","선택 모델과 원본 입력으로 권장값을 다시 분석 중입니다."); try { const analysis=await analyseDraft(draft.input,await storage.imageInputs(draft.input.imageIds)); const accepted=new Map(draft.questions.filter((item)=>["accepted","overridden"].includes(item.status)).map((item)=>[item.path,item])); draft.product=analysis.product; draft.components=analysis.components; draft.questions=analysis.questions.map((item)=>{const prior=accepted.get(item.path); return prior?{...item,status:prior.status,userValue:prior.userValue}:item;}); draft.stickerSlots=analysis.stickerSlots; await saveDraft(draft,"awaiting_parameter_review","권장값을 갱신했습니다. 새 값과 오래된 의존값을 확인하세요."); return res.json({ok:true,draft:publicDraft(draft)}); } catch(error) { await saveDraft(draft,"failed",error instanceof Error?error.message:String(error)); return res.status(400).json({ok:false,error:error.message,draft:publicDraft(draft)}); }});
app.post("/api/modeling/drafts/:id/build",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); const draft=await drafts.get(req.params.id); if(!draft) return res.status(404).json({ok:false,error:"초안을 찾을 수 없습니다."}); if(req.body?.expectedRevision!==draft.revision||req.body?.approvalHash!==approvalHash(draft)) return res.status(409).json({ok:false,error:"승인 상태가 최신이 아닙니다.",draft:publicDraft(draft)}); const ready=draftReady(draft); if(!ready.ready) return res.status(409).json({ok:false,error:"approval_incomplete",questionIds:ready.blockers,draft:publicDraft(draft)}); try { if(draft.jobId&&draft.buildApprovalHash===approvalHash(draft)) { const existing=await getJob(draft.jobId); if(existing&&!["failed"].includes(existing.state)) return res.status(202).json({ok:true,job:publicJob(existing),statusUrl:`/api/modeling/jobs/${existing.id}`,eventsUrl:`/api/modeling/jobs/${existing.id}/events`}); } const payload=approvedDraftToLegacyPayload(draft); await saveDraft(draft,"building","승인된 기준값으로 Blender 생성을 시작했습니다."); const job=await queueJob(payload,{draft}); draft.jobId=job.id; draft.buildApprovalHash=approvalHash(draft); await drafts.save(draft); await progressDraft(draft,{operation:"build",stage:"승인 명세 컴파일",state:"complete",message:"승인된 기준값을 안전한 모델링 명세로 컴파일했습니다."}); await progressDraft(draft,{operation:"build",stage:"CAD·Blender 생성",state:"running",completed:0,total:payload.components.length,unit:"components",message:"선택한 컴포넌트 생성을 시작했습니다."}); return res.status(202).json({ok:true,job:publicJob(job),statusUrl:`/api/modeling/jobs/${job.id}`,eventsUrl:`/api/modeling/jobs/${job.id}/events`}); } catch(error) { await saveDraft(draft,"failed",error.message); return res.status(400).json({ok:false,error:error.message,draft:publicDraft(draft)}); }});
app.post("/api/modeling/jobs",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); return res.status(409).json({ok:false,error:"approval_required: 직접 jobs 실행은 허용되지 않습니다. 저장된 draftId·revision·approvalHash로 /api/modeling/drafts/:id/build를 사용하세요."}); });
app.get("/api/modeling/jobs/:id",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); const job=await getJob(req.params.id); return job?res.json({ok:true,job:publicJob(job)}):res.status(404).json({ok:false,error:"작업을 찾을 수 없습니다."}); });
app.get("/api/modeling/jobs/:id/events",async(req,res)=>{ if(!authorized(req)) return res.status(401).end(); const job=await getJob(req.params.id); if(!job) return res.status(404).end(); res.set({"content-type":"text/event-stream","cache-control":"no-cache",connection:"keep-alive"}); res.flushHeaders(); for(const item of job.events) res.write(`data: ${JSON.stringify(item)}\n\n`); if(["complete","review_required","failed"].includes(job.state)) return res.end(); job.clients.add(res); req.on("close",()=>job.clients.delete(res)); });
app.post("/api/modeling/jobs/:id/input",async(req,res)=>{ const job=await getJob(req.params.id); if(!job) return res.status(404).json({ok:false,error:"작업을 찾을 수 없습니다."}); if(job.state!=="awaiting_input") return res.status(409).json({ok:false,error:"이 작업은 추가 입력을 기다리고 있지 않습니다."}); event(job,"planning","추가 입력을 받았습니다. 계획을 재개합니다."); return res.json({ok:true,job:publicJob(job)}); });
app.get("/api/modeling/jobs/:id/artifacts/{*path}",serveArtifact);
app.get("/api/modeling/showcase",async(_req,res)=>res.json({ok:true,showcase:await versions.showcase()}));
app.get("/api/modeling/showcase/artifact",async(_req,res)=>serveGlb(res,versions.showcaseArtifactPath(),"홈에 표시할 모델링 자산이 없습니다."));
app.post("/api/modeling/assemblies/preview",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); try { const assembly=await assembleSelections(req.body?.selections); return res.json({ok:true,assembly:{...assembly,assetPath:`/api/modeling/assemblies/${assembly.id}/artifact`}}); } catch(error) { return res.status(400).json({ok:false,error:error.message}); }});
app.get("/api/modeling/assemblies/:id/artifact",async(req,res)=>serveGlb(res,versions.assemblyPath(req.params.id),"선택한 조립 모델을 찾을 수 없습니다."));
app.post("/api/modeling/showcase",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); try { const body=req.body??{}; const raw=Array.isArray(body.selections) ? body.selections : [{component:body.component,versionId:body.versionId}]; const assembly=await assembleSelections(raw); return res.json({ok:true,showcase:await versions.setShowcase({selections:assembly.components,sourcePath:assembly.sourcePath})}); } catch(error) { return res.status(400).json({ok:false,error:error.message}); }});
app.get("/api/modeling/components/:component/versions",async(req,res)=>{ try { return res.json({ok:true,versions:await versions.list(req.params.component)}); } catch(error) { return res.status(400).json({ok:false,error:error.message}); }});
app.get("/api/modeling/components/:component/versions/:versionId",async(req,res)=>{ const version=await versions.find(req.params.component,req.params.versionId); return version?res.json({ok:true,version}):res.status(404).json({ok:false,error:"버전을 찾을 수 없습니다."}); });
app.get("/api/modeling/components/:component/versions/:versionId/artifact",async(req,res)=>{ const version=await versions.find(req.params.component,req.params.versionId); const file=versions.artifactPath(req.params.component,req.params.versionId); if(!version||!existsSync(file)) return res.status(404).json({ok:false,error:"버전 자산을 찾을 수 없습니다."}); res.set({"content-type":"model/gltf-binary","cache-control":"no-store","cross-origin-resource-policy":"cross-origin"}); return createReadStream(file).pipe(res); });
app.patch("/api/modeling/components/:component/versions/:versionId",async(req,res)=>{ const previous=await versions.find(req.params.component,req.params.versionId); if(!previous) return res.status(404).json({ok:false,error:"버전을 찾을 수 없습니다."}); return res.status(409).json({ok:false,error:"approval_required: 저장된 자산 수정은 새 승인 초안(/api/modeling/drafts)에서 시작해야 합니다.",version:previous}); });
app.delete("/api/modeling/components/:component/versions/:versionId",async(req,res)=>{ try { const removed=await versions.remove(req.params.component,req.params.versionId); return removed?res.json({ok:true,removed}):res.status(404).json({ok:false,error:"버전을 찾을 수 없습니다."}); } catch(error) { return res.status(400).json({ok:false,error:error.message}); }});
app.post("/mcp",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"MCP bearer token이 필요합니다."}); try { const server=createBlenderMcpServer({assetRoot}); const transport=new NodeStreamableHTTPServerTransport({sessionIdGenerator:undefined}); await server.connect(transport); await transport.handleRequest(req,res,req.body); } catch(error) { if(!res.headersSent) res.status(500).json({ok:false,error:error.message}); }});
const port=Number(process.env.NET30_MODELING_HUB_PORT??process.env.PORT??8788); app.listen(port,process.env.HOST??"127.0.0.1",()=>console.log(`NET30 modeling hub listening on ${port}`));
