import "dotenv/config";
import { createReadStream, existsSync } from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";
import express from "express";
import cors from "cors";
import { NodeStreamableHTTPServerTransport } from "@modelcontextprotocol/node";
import { createBlenderMcpServer, modelingPayloadSchema } from "./blender-mcp.mjs";
import { runModelingJob } from "./modeling-agent.mjs";
import { createAssetStorage, IMAGE_TYPES, MAX_IMAGE_BYTES } from "./storage.mjs";
import { COMPONENTS, JOB_STATES, defaultOpenAiModel, openAiModels } from "./modeling-spec.mjs";

const app = express(); const token = (process.env.NET30_MODELING_HUB_TOKEN ?? "").trim();
const origins = (process.env.NET30_MODELING_ALLOWED_ORIGINS ?? "http://127.0.0.1:5173").split(",").map((value) => value.trim()).filter(Boolean);
const env = (name, fallback = "") => process.env[name]?.trim() || fallback;
const repoRoot = env("NET30_REPO", path.resolve(process.cwd(), "../../../..")); const assetRoot = env("NET30_3D_ASSET_ROOT", path.resolve(repoRoot, "../net30-3d-assets")); const jobsRoot = path.join(assetRoot, "jobs"); const storage = createAssetStorage(assetRoot);
const jobs = new Map();
function authorized(req) { if (!token) return true; const local=["127.0.0.1","::1","::ffff:127.0.0.1"].includes(req.socket.remoteAddress ?? ""); return (local && ["http://127.0.0.1:5173","http://localhost:5173"].includes(req.headers.origin ?? "")) || req.headers.authorization === `Bearer ${token}`; }
function event(job, state, message) { job.state=state; job.message=message; job.updatedAt=new Date().toISOString(); job.events.push({ state,message,at:job.updatedAt }); for (const client of job.clients) client.write(`data: ${JSON.stringify({ state,message,at:job.updatedAt })}\n\n`); }
function publicJob(job) { const { clients, promise, ...value }=job; return value; }
async function getJob(id) { if (jobs.has(id)) return jobs.get(id); const file=path.join(jobsRoot,id,"result.json"); if (!existsSync(file)) return null; const result=JSON.parse(await fs.readFile(file,"utf8")); return { id, state:"complete", message:"저장된 작업", createdAt:"", updatedAt:"", events:[], result }; }
async function serveArtifact(req,res) { const id=req.params.id; const part=(Array.isArray(req.params.path) ? req.params.path.join("/") : req.params.path ?? "").replace(/^\/+/,""); if (!part || part.includes("..")) return res.status(400).json({ok:false,error:"잘못된 artifact 경로입니다."}); const file=path.resolve(jobsRoot,id,part); if (!file.startsWith(`${path.resolve(jobsRoot,id)}${path.sep}`) || !existsSync(file)) return res.status(404).json({ok:false,error:"artifact를 찾을 수 없습니다."}); const ext=path.extname(file); res.set({"content-type":ext===".glb"?"model/gltf-binary":ext===".json"?"application/json":"application/octet-stream","cache-control":"no-store","cross-origin-resource-policy":"cross-origin"}); return createReadStream(file).pipe(res); }

await fs.mkdir(jobsRoot,{recursive:true}); await storage.initialise(); await storage.cleanupExpired(); setInterval(()=>void storage.cleanupExpired(),3600000).unref();
app.use(cors({origin(origin,cb){ if(!origin||origins.includes(origin)) return cb(null,true); return cb(new Error(`허용되지 않은 origin: ${origin}`)); }})); app.use(express.json({limit:"1mb"}));
app.get("/health",(_req,res)=>res.json({ok:true,mode:"assembly-cad-blender-v2",openAiModels:openAiModels(),storage:process.env.AWS_S3_BUCKET_NAME?"railway-bucket":"local-volume",jobStates:JOB_STATES}));
app.get("/api/modeling/schema",(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); return res.json({ok:true,components:COMPONENTS,models:openAiModels(),defaultModel:defaultOpenAiModel(),upload:{maxFiles:4,maxBytes:MAX_IMAGE_BYTES,types:[...IMAGE_TYPES]},manufacturing:"engineer-reviewed candidate only"}); });
app.post("/api/modeling/uploads",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); try { const upload=await storage.createUpload(req.body??{}); return res.status(201).json({ok:true,upload}); } catch(error) { return res.status(400).json({ok:false,error:error.message}); }});
app.put("/api/modeling/uploads/:id",express.raw({type:()=>true,limit:"10mb"}),async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); try { if(!IMAGE_TYPES.has(req.headers["content-type"]??"")) throw new Error("JPEG, PNG, WebP 이미지만 업로드할 수 있습니다."); const upload=await storage.putLocal(req.params.id,req.body,req.headers["content-type"]); return res.json({ok:true,upload:{id:upload.id}}); } catch(error) { return res.status(400).json({ok:false,error:error.message}); }});
app.post("/api/modeling/uploads/:id/complete",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); try { const upload=await storage.markUploaded(req.params.id); return res.json({ok:true,upload:{id:upload.id}}); } catch(error) { return res.status(400).json({ok:false,error:error.message}); }});
app.post("/api/modeling/jobs",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); try { const payload=modelingPayloadSchema.parse(req.body??{}); const id=`job-${Date.now()}-${Math.random().toString(36).slice(2,8)}`; const job={id,state:"researching",message:"작업을 대기열에 추가했습니다.",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),events:[],clients:new Set(),result:null}; jobs.set(id,job); const imageInputs=await storage.imageInputs(payload.imageIds); job.promise=runModelingJob(payload,{jobId:id,imageInputs,onProgress:(state,message)=>event(job,state,message)}).then((result)=>{job.result=result; if(job.state!=="review_required") event(job,result.status,"작업이 완료되었습니다."); return result;}).catch((error)=>{job.error=error.message; event(job,"failed",error.message);}).finally(()=>{for(const client of job.clients) client.end(); job.clients.clear();}); return res.status(202).json({ok:true,job:publicJob(job),statusUrl:`/api/modeling/jobs/${id}`,eventsUrl:`/api/modeling/jobs/${id}/events`}); } catch(error) { return res.status(400).json({ok:false,error:error.message}); }});
app.get("/api/modeling/jobs/:id",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"인증되지 않은 요청입니다."}); const job=await getJob(req.params.id); return job?res.json({ok:true,job:publicJob(job)}):res.status(404).json({ok:false,error:"작업을 찾을 수 없습니다."}); });
app.get("/api/modeling/jobs/:id/events",async(req,res)=>{ if(!authorized(req)) return res.status(401).end(); const job=await getJob(req.params.id); if(!job) return res.status(404).end(); res.set({"content-type":"text/event-stream","cache-control":"no-cache",connection:"keep-alive"}); res.flushHeaders(); for(const item of job.events) res.write(`data: ${JSON.stringify(item)}\n\n`); if(["complete","review_required","failed"].includes(job.state)) return res.end(); job.clients.add(res); req.on("close",()=>job.clients.delete(res)); });
app.post("/api/modeling/jobs/:id/input",async(req,res)=>{ const job=await getJob(req.params.id); if(!job) return res.status(404).json({ok:false,error:"작업을 찾을 수 없습니다."}); if(job.state!=="awaiting_input") return res.status(409).json({ok:false,error:"이 작업은 추가 입력을 기다리고 있지 않습니다."}); event(job,"planning","추가 입력을 받았습니다. 계획을 재개합니다."); return res.json({ok:true,job:publicJob(job)}); });
app.get("/api/modeling/jobs/:id/artifacts/{*path}",serveArtifact);
app.post("/mcp",async(req,res)=>{ if(!authorized(req)) return res.status(401).json({ok:false,error:"MCP bearer token이 필요합니다."}); try { const server=createBlenderMcpServer({assetRoot}); const transport=new NodeStreamableHTTPServerTransport({sessionIdGenerator:undefined}); await server.connect(transport); await transport.handleRequest(req,res,req.body); } catch(error) { if(!res.headersSent) res.status(500).json({ok:false,error:error.message}); }});
const port=Number(process.env.PORT??process.env.NET30_MODELING_HUB_PORT??8788); app.listen(port,process.env.HOST??"127.0.0.1",()=>console.log(`NET30 modeling hub listening on ${port}`));
