import type { ProductPageDefinition } from "../../../docs/design-system/entry";
import { net30Definition } from "../sku-data";

const serviceOrigin = import.meta.env.VITE_NET30_3D_SERVICE_URL ?? "/3d";
const embeddedHostOrigin = typeof window === "undefined" ? "" : `&hostOrigin=${encodeURIComponent(window.location.origin)}`;

export const modelPageDefinition: ProductPageDefinition = {
  ...net30Definition,
  regions: ["header", "catalog", "footer"],
  meta: {
    title: "NET30 — 3D 모델링 스튜디오",
    description: "Blender MCP를 사용해 NET30 제품 3D 자산을 컴포넌트별로 관리합니다.",
  },
  system: {
    ...net30Definition.system,
    topId: net30Definition.system.catalogId,
  },
  brand: {
    ...net30Definition.brand,
    tagline: "제품 데이터와 Blender 원본을 분리한 3D 자산 관리",
  },
  navigation: [],
  catalogSection: {
    label: "3D MODELING STUDIO",
    title: ["프롬프트와 이미지로", "기준값부터 검증합니다."],
    copy: [
      "OpenAI가 제품과 구성 부품을 제안하고, 사용자가 각 기준값을 검증한 뒤에만 Blender가 GLB를 생성합니다.",
    ],
  },
  catalog: {
    ...net30Definition.catalog,
    presentation: "modeling",
    modeling: {
      endpoint: "/api/modeling/jobs",
      previewSrc: `${serviceOrigin}/?${embeddedHostOrigin.slice(1)}`,
      downloadSrc: "",
      title: "OpenAI × Blender",
      copy: "이미지는 모델링 의도 분석에만 사용됩니다. OpenAI는 구조화된 권장값을 제안하며, 모든 필수값을 승인하기 전에는 Blender를 실행하지 않습니다.",
      backLabel: "Storefront로 돌아가기",
      submitLabel: "제품·부품 분석 시작",
      pendingLabel: "모델링 작업 진행 중",
      previewTitle: "3D 미리보기",
      resultTitle: "최근 실행 결과",
      downloadLabel: "현재 GLB 다운로드",
      idleMessage: "아직 실행한 모델링 작업이 없습니다.",
      unavailableMessage: "모델링 서비스가 일시적으로 준비되지 않아도, 저장된 3D 자산 미리보기는 계속 표시됩니다.",
      workspace: {
        productLabel: "제품",
        productName: "DURAN GL45 100 mL 실험용 병",
        productDescription: "완성 제품을 기준으로 구성 부품, 제조 자료, 공개 자산을 한 작업 공간에서 관리합니다.",
        assemblyLabel: "완성 조립 모델",
        assemblyDescription: "병·마개·밀봉·그래픽이 공통 조립 계약으로 연결된 최종 제품 자산입니다.",
        componentsLabel: "구성 부품",
        manufacturingLabel: "제조·검증 자료",
        publicationLabel: "공개·배포",
      },
      assetLibrary: {
        title: "제품 자산 라이브러리",
        copy: "각 컴포넌트 버전을 작은 3D 미리보기로 확인하고, 선택한 항목은 이 라이브러리 안에서 조립해 검토·홈 게시합니다.",
        emptyMessage: "저장된 버전이 없습니다.",
        selectionLabel: "조립에 포함",
        selectionEmptyMessage: "조립에 포함할 저장 버전을 선택하세요.",
        selectionTitle: "조립 선택",
        selectionSummary: (count) => `${count}개 컴포넌트 버전이 조립에 포함됩니다.`,
        previewTitle: "선택한 항목 미리보기",
        previewIdleMessage: "카드를 선택하면 선택한 항목을 이 영역에서 조립해 크게 미리 봅니다.",
        previewPendingMessage: "선택한 항목을 조립해 미리보기를 갱신하고 있습니다.",
        previewLabel: "선택한 항목 미리보기",
        editLabel: "수정 시작",
        homeLabel: "선택 항목을 홈에 표시",
        deleteLabel: "삭제",
      },
      fields: {
        model: "OpenAI 모델",
        images: "모델링 입력 이미지",
        component: "컴포넌트",
        sku: "SKU",
        material: "재질",
        shape: "형상",
        sizeXmm: "폭(mm)",
        sizeYmm: "높이(mm)",
        sizeZmm: "깊이(mm)",
        shellThicknessMm: "두께(mm)",
        distortion: "왜곡 정도",
        tone: "대표 색상",
        finish: "마감",
        prompt: "모델링 프롬프트",
      },
      components: [
        { id: "bottle", label: "유리병" },
        { id: "cap", label: "뚜껑" },
        { id: "pouringRing", label: "푸어링 링" },
        { id: "liner", label: "밀봉 라이너" },
        { id: "decorationFront", label: "전면 인쇄" },
        { id: "decorationBack", label: "후면 인쇄" },
        { id: "contents", label: "내용물" },
      ],
      componentGroups: [
        { id: "container", label: "용기", description: "제품의 외형과 내부 공동을 이루는 부품", componentIds: ["bottle"] },
        { id: "closure", label: "마개·밀봉", description: "개폐, 접촉, 밀봉을 담당하는 부품", componentIds: ["cap", "pouringRing", "liner"] },
        { id: "graphics", label: "그래픽", description: "표면 인쇄와 장식 요소", componentIds: ["decorationFront", "decorationBack"] },
        { id: "contents", label: "내용물", description: "선택한 경우에만 생성되는 내부 구성", componentIds: ["contents"] },
      ],
      materials: [
        { id: "glass", label: "유리" },
        { id: "opaque-plastic", label: "불투명 플라스틱" },
        { id: "paper", label: "종이 라벨" },
        { id: "tablet", label: "정제" },
        { id: "capsule", label: "캡슐" },
        { id: "softgel", label: "소프트젤" },
        { id: "custom", label: "사용자 정의" },
      ],
      shapes: [
        { id: "cylindrical", label: "원통형" },
        { id: "short-wide", label: "짧고 넓은 형상" },
        { id: "tall-slim", label: "길고 좁은 형상" },
        { id: "ribbed", label: "리브형" },
        { id: "custom", label: "사용자 정의" },
      ],
      defaults: {
        modelId: "",
        componentIds: ["bottle", "cap", "pouringRing", "decorationFront"],
        materialId: "glass",
        shapeId: "cylindrical",
        sizeXmm: 45,
        sizeYmm: 92,
        sizeZmm: 45,
        shellThicknessMm: 2.5,
        distortion: 0.12,
        tone: "#2d5fc4",
        finish: "high-gloss",
        prompt: "DURAN Original GL 45 100 mL 실험용 유리병과 청색 PP 리브 캡, 푸어링 링, 백색 인쇄 눈금을 생성하세요. 병·캡·링의 조립 규격을 공통으로 유지하고, 별도 내외벽과 둥근 숄더·힐을 표현하세요.",
      },
    },
  },
};
