import type { ProductPageDefinition } from "../../../docs/design-system/entry";
import { net30Definition } from "../sku-data";

const serviceOrigin = import.meta.env.VITE_NET30_3D_SERVICE_URL ?? "/3d";
const embeddedHostOrigin = typeof window === "undefined" ? "" : `&hostOrigin=${encodeURIComponent(window.location.origin)}`;

export const modelPageDefinition: ProductPageDefinition = {
  ...net30Definition,
  regions: ["header", "catalog", "footer"],
  meta: {
    title: "NET30 — 3D 모델링 스튜디오",
    description: "Blender MCP를 사용해 NET30 제품 3D 자산을 컴포넌트별로 관리합니다.",
  },
  system: {
    ...net30Definition.system,
    topId: net30Definition.system.catalogId,
  },
  brand: {
    ...net30Definition.brand,
    tagline: "제품 데이터와 Blender 원본을 분리한 3D 자산 관리",
  },
  navigation: [],
  catalogSection: {
    label: "3D MODELING STUDIO",
    title: ["프롬프트와 이미지로", "3D 자산을 생성합니다."],
    copy: [
      "텍스트 지시와 선택적 이미지 입력을 OpenAI가 구조화하고, 검증된 Blender 파이프라인이 런타임 GLB로 내보냅니다.",
    ],
  },
  catalog: {
    ...net30Definition.catalog,
    presentation: "modeling",
    modeling: {
      endpoint: "/api/modeling/jobs",
      previewSrc: `${serviceOrigin}/?${embeddedHostOrigin.slice(1)}`,
      downloadSrc: "",
      title: "OpenAI × Blender",
      copy: "이미지는 선택적 모델링 입력입니다. OpenAI가 안전한 구조 명세를 만들고 headless Blender가 GLB를 생성합니다.",
      backLabel: "Storefront로 돌아가기",
      submitLabel: "모델링 실행",
      pendingLabel: "모델링 작업 진행 중",
      previewTitle: "3D 미리보기",
      resultTitle: "최근 실행 결과",
      downloadLabel: "현재 GLB 다운로드",
      idleMessage: "아직 실행한 모델링 작업이 없습니다.",
      unavailableMessage: "모델링 서비스가 일시적으로 준비되지 않아도, 저장된 3D 자산 미리보기는 계속 표시됩니다.",
      assetLibrary: {
        title: "저장된 모델링 자산",
        copy: "컴포넌트별 이전 버전을 미리보고, 선택한 버전을 바탕으로 수정 작업을 시작할 수 있습니다.",
        emptyMessage: "저장된 버전이 없습니다.",
        previewLabel: "미리보기",
        editLabel: "수정 시작",
        deleteLabel: "삭제",
      },
      fields: {
        model: "OpenAI 모델",
        images: "모델링 입력 이미지",
        component: "컴포넌트",
        sku: "SKU",
        material: "재질",
        shape: "형상",
        sizeXmm: "폭(mm)",
        sizeYmm: "높이(mm)",
        sizeZmm: "깊이(mm)",
        shellThicknessMm: "두께(mm)",
        distortion: "왜곡 정도",
        tone: "대표 색상",
        finish: "마감",
        prompt: "모델링 프롬프트",
      },
      components: [
        { id: "bottle", label: "유리병" },
        { id: "cap", label: "뚜껑" },
        { id: "pouringRing", label: "푸어링 링" },
        { id: "liner", label: "밀봉 라이너" },
        { id: "decorationFront", label: "전면 인쇄" },
        { id: "decorationBack", label: "후면 인쇄" },
        { id: "contents", label: "내용물" },
      ],
      materials: [
        { id: "glass", label: "유리" },
        { id: "opaque-plastic", label: "불투명 플라스틱" },
        { id: "paper", label: "종이 라벨" },
        { id: "tablet", label: "정제" },
        { id: "capsule", label: "캡슐" },
        { id: "softgel", label: "소프트젤" },
        { id: "custom", label: "사용자 정의" },
      ],
      shapes: [
        { id: "cylindrical", label: "원통형" },
        { id: "short-wide", label: "짧고 넓은 형상" },
        { id: "tall-slim", label: "길고 좁은 형상" },
        { id: "ribbed", label: "리브형" },
        { id: "custom", label: "사용자 정의" },
      ],
      defaults: {
        modelId: "",
        componentIds: ["bottle", "cap", "pouringRing", "decorationFront"],
        materialId: "glass",
        shapeId: "cylindrical",
        sizeXmm: 45,
        sizeYmm: 92,
        sizeZmm: 45,
        shellThicknessMm: 2.5,
        distortion: 0.12,
        tone: "#2d5fc4",
        finish: "high-gloss",
        prompt: "DURAN Original GL 45 100 mL 실험용 유리병과 청색 PP 리브 캡, 푸어링 링, 백색 인쇄 눈금을 생성하세요. 병·캡·링의 조립 규격을 공통으로 유지하고, 별도 내외벽과 둥근 숄더·힐을 표현하세요.",
      },
    },
  },
};
